// Generated by gencpp from file state_machine/CommandResponse.msg
// DO NOT EDIT!


#ifndef STATE_MACHINE_MESSAGE_COMMANDRESPONSE_H
#define STATE_MACHINE_MESSAGE_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_machine
{
template <class ContainerAllocator>
struct CommandResponse_
{
  typedef CommandResponse_<ContainerAllocator> Type;

  CommandResponse_()
    : response()  {
    }
  CommandResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::state_machine::CommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_machine::CommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandResponse_

typedef ::state_machine::CommandResponse_<std::allocator<void> > CommandResponse;

typedef boost::shared_ptr< ::state_machine::CommandResponse > CommandResponsePtr;
typedef boost::shared_ptr< ::state_machine::CommandResponse const> CommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_machine::CommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_machine::CommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_machine::CommandResponse_<ContainerAllocator1> & lhs, const ::state_machine::CommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_machine::CommandResponse_<ContainerAllocator1> & lhs, const ::state_machine::CommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_machine

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_machine::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_machine::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_machine::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::state_machine::CommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::state_machine::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_machine/CommandResponse";
  }

  static const char* value(const ::state_machine::CommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_machine::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::state_machine::CommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_machine::CommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_machine::CommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_machine::CommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_MACHINE_MESSAGE_COMMANDRESPONSE_H
